package com.credite;

public class service {
    //PE SCURT AICI VOI PUNE NISTE METODE DE ACCES RAPID LA INFORMATII DIN SISTEMUL PE CARE IL FAC
    //EX: NUME CLIENT - RATA LUNARA - NR LUNI RAMASE - TOTAL PLATA RAMAS
    //CA CE S-AR PUTEA ARATA CAND UN ADMIN VREA SA OBTINA INFORMATII RAPID; NEW IDEAS TBA
}
